@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION
SET FROM=%~dp1
FOR %%R IN ("%~2%~3") DO (
	SET TO=%%~dpR
	SET FILENAME=%%~nxR
	SET CMDLINE="!FROM!" "!TO!" "!FILENAME!"
	ECHO ROBOCOPY !CMDLINE:\"="!
	ROBOCOPY !CMDLINE:\"="! /COPYALL /SL
)
ENDLOCAL